---
- name: Download k9s for Mac (Apple Silicon)
  ansible.builtin.get_url:
    url: https://github.com/derailed/k9s/releases/latest/download/k9s_Linux_arm64.tar.gz
    dest: /tmp/k9s_Linux_arm64.tar.gz
    mode: '0644'

- name: extract k9s tar.gz
  ansible.builtin.unarchive:
    src: /tmp/k9s_Linux_arm64.tar.gz
    dest: /usr/local/bin
    remote_src: yes
