---
- hosts: masters
  become: true
  become_method: sudo
  gather_facts: yes

  vars_prompt:
  - name: "github_token"
    prompt: "Please paste your GitHub Personal Access Token (PAT)"
    private: yes

  roles:
    - helm
    - k9s
    - flux
