---
- name: Install required packages for k3s
  apt:
    pkg:
      - net-tools
      - curl
    state: latest
    update_cache: true 

- name: Fix resolv.conf
  copy:
    dest: /etc/resolv.conf
    content: |
      nameserver 8.8.8.8
      nameserver 1.1.1.1
    mode: '0644'
