---
- name: Download helm
  get_url:
    url: https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
    dest: /tmp/get_helm.sh
    mode: '0777'
  when: "'masters' in group_names"

- name: install helm 
  shell: /tmp/get_helm.sh
  when: "'masters' in group_names"

- name: add ingress-nginx repo to helm
  shell: helm repo add ingress-nginx https://helm.nginx.com/stable
    #  kubernetes.core.helm_repository:
    #    repo_name: "nginx-stable"
    #    repo_url: "https://helm.nginx.com/stable"
    #    repo_state: present


- name: Update repository cache
  shell: helm repo update
    #  #  kubernetes.core.helm:
    #  #    name: nginx-stable
    #  #    namespace: kube-system
    #  #    state: absent
    #
    #  update_repo_cache: true
- name: install ingress-nginx
  kubernetes.core.helm:
    name: ingress-nginx
    chart_ref: "nginx-stable/nginx-ingress"
    release_namespace: nginx-ingress
    create_namespace: true
    release_state: present
    values:
      controller:
        service:
          create: true
          type: NodePort
