---
- name: Download k3s installer
  get_url:
    url: https://get.k3s.io
    dest: /tmp/get_k3s.sh
    mode: '0755'

- name: Configure k3s master
  block:
    - name: Ensure k3s is not installed
      shell: |
        /usr/local/bin/k3s-uninstall.sh || true
      ignore_errors: yes
      when: "'masters' in group_names"

    - name: Install k3s binary on master
      shell: /tmp/get_k3s.sh
      environment:
        K3S_TOKEN: "{{ node_token }}"
        INSTALL_K3S_EXEC: "server \
                           --disable=traefik \
                           --flannel-backend=host-gw \
                           --tls-san={{ ansible_host }} \
                           --bind-address={{ ansible_host }} \
                           --advertise-address={{ ansible_host }} \
                           --node-ip={{ ansible_host }} \
                           --cluster-init"
      register: k3s_install_result
      changed_when: k3s_install_result.stdout != ""
      failed_when: k3s_install_result.rc != 0
      when: "'masters' in group_names"

    - name: Ensure k3s service is started and enabled
      systemd:
        name: k3s
        state: started
        enabled: yes
      when: "'masters' in group_names"

- name: Add worker nodes
  block:
    - name: Wait for master node token to be available
      wait_for:
        timeout: 30
      when: "'workers' in group_names"

    - name: Join worker node to the cluster
      shell: /tmp/get_k3s.sh agent
      environment:
        K3S_URL: "https://{{ hostvars['master0'].ansible_host }}:6443"
        K3S_TOKEN: "{{ node_token }}"
      register: k3s_install_result
      changed_when: k3s_install_result.stdout != ""
      failed_when: k3s_install_result.rc != 0
  when: "'workers' in group_names"
